-- Meeting Rooms Information --
INSERT INTO MEETING_ROOM (ID, NAME, CAPACITY) VALUES ('01', 'ASIA ROOM', 10);
INSERT INTO MEETING_ROOM (ID, NAME, CAPACITY) VALUES ('02', 'AFRICA ROOM', 10);
INSERT INTO MEETING_ROOM (ID, NAME, CAPACITY) VALUES ('03', 'NORTH AMERICA ROOM', 8);
INSERT INTO MEETING_ROOM (ID, NAME, CAPACITY) VALUES ('04', 'SOUTH AMERICA ROOM', 8);
INSERT INTO MEETING_ROOM (ID, NAME, CAPACITY) VALUES ('05', 'ANTARCTICA ROOM', 6);
INSERT INTO MEETING_ROOM (ID, NAME, CAPACITY) VALUES ('06', 'EUROPE ROOM', 6);
INSERT INTO MEETING_ROOM (ID, NAME, CAPACITY) VALUES ('07', 'AUSTRALIA ROOM', 4);


-- Meeting Room Timings --
INSERT INTO TIMINGS (TIME_ID, TIME_SLOT, ROOM_ID, IS_AVAILABLE) values ('101', '9:00 - 10:00', '01', true);
INSERT INTO TIMINGS (TIME_ID, TIME_SLOT, ROOM_ID, IS_AVAILABLE) values ('201', '10:00 - 11:00', '01', true);
INSERT INTO TIMINGS (TIME_ID, TIME_SLOT, ROOM_ID, IS_AVAILABLE) values ('301', '11:00 - 12:00', '01', true);
INSERT INTO TIMINGS (TIME_ID, TIME_SLOT, ROOM_ID, IS_AVAILABLE) values ('102', '9:00 - 10:00', '02', true);
INSERT INTO TIMINGS (TIME_ID, TIME_SLOT, ROOM_ID, IS_AVAILABLE) values ('202', '10:00 - 11:00', '02', true);
INSERT INTO TIMINGS (TIME_ID, TIME_SLOT, ROOM_ID, IS_AVAILABLE) values ('302', '11:00 - 12:00', '02', true);
INSERT INTO TIMINGS (TIME_ID, TIME_SLOT, ROOM_ID, IS_AVAILABLE) values ('103', '9:00 - 10:00', '03', true);
INSERT INTO TIMINGS (TIME_ID, TIME_SLOT, ROOM_ID, IS_AVAILABLE) values ('203', '10:00 - 11:00', '03', true);
INSERT INTO TIMINGS (TIME_ID, TIME_SLOT, ROOM_ID, IS_AVAILABLE) values ('303', '11:00 - 12:00', '03', true);
INSERT INTO TIMINGS (TIME_ID, TIME_SLOT, ROOM_ID, IS_AVAILABLE) values ('104', '9:00 - 10:00', '04', true);
INSERT INTO TIMINGS (TIME_ID, TIME_SLOT, ROOM_ID, IS_AVAILABLE) values ('204', '10:00 - 11:00', '04', true);
INSERT INTO TIMINGS (TIME_ID, TIME_SLOT, ROOM_ID, IS_AVAILABLE) values ('304', '11:00 - 12:00', '04', true);
INSERT INTO TIMINGS (TIME_ID, TIME_SLOT, ROOM_ID, IS_AVAILABLE) values ('105', '9:00 - 10:00', '05', true);
INSERT INTO TIMINGS (TIME_ID, TIME_SLOT, ROOM_ID, IS_AVAILABLE) values ('205', '10:00 - 11:00', '05', true);
INSERT INTO TIMINGS (TIME_ID, TIME_SLOT, ROOM_ID, IS_AVAILABLE) values ('305', '11:00 - 12:00', '05', true);
INSERT INTO TIMINGS (TIME_ID, TIME_SLOT, ROOM_ID, IS_AVAILABLE) values ('106', '9:00 - 10:00', '06', true);
INSERT INTO TIMINGS (TIME_ID, TIME_SLOT, ROOM_ID, IS_AVAILABLE) values ('206', '10:00 - 11:00', '06', true);
INSERT INTO TIMINGS (TIME_ID, TIME_SLOT, ROOM_ID, IS_AVAILABLE) values ('306', '11:00 - 12:00', '06', true);
INSERT INTO TIMINGS (TIME_ID, TIME_SLOT, ROOM_ID, IS_AVAILABLE) values ('107', '9:00 - 10:00', '07', true);
INSERT INTO TIMINGS (TIME_ID, TIME_SLOT, ROOM_ID, IS_AVAILABLE) values ('207', '10:00 - 11:00', '07', true);
INSERT INTO TIMINGS (TIME_ID, TIME_SLOT, ROOM_ID, IS_AVAILABLE) values ('307', '11:00 - 12:00', '07', true);